# Generated by Django 3.1.6 on 2021-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Event')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='venue',
            name='events',
        ),
        migrations.AddField(
            model_name='venue',
            name='events',
            field=models.ManyToManyField(default=None, to='main.Events', verbose_name='Events that can be organized'),
        ),
    ]
