# Generated by Django 3.1.6 on 2021-03-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ordered Date')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venue', verbose_name='Name of the Venue')),
            ],
        ),
    ]
