# Generated by Django 3.1.6 on 2021-03-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orderdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDate',
        ),
    ]
