# Generated by Django 3.1.6 on 2021-03-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210302_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDate',
        ),
    ]
