# Generated by Django 3.1.6 on 2021-03-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210303_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='venue_name',
            new_name='name',
        ),
    ]
