# Generated by Django 3.1.7 on 2021-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210303_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_events',
            field=models.ManyToManyField(to='main.Event', verbose_name='Selected Events'),
        ),
    ]
