# Generated by Django 3.1.7 on 2021-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210305_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_full_name',
            field=models.CharField(default='Bimal', max_length=150, verbose_name='Full name of User'),
            preserve_default=False,
        ),
    ]
